In [1]:
# https://deeplearningcourses.com/c/deep-reinforcement-learning-in-python
# https://www.udemy.com/deep-reinforcement-learning-in-python
import gym
# Wiki:
# https://github.com/openai/gym/wiki/CartPole-v0
# Environment page:
# https://gym.openai.com/envs/CartPole-v0

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ale_py/roms/utils.py:90: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for external in metadata.entry_points().get(self.group, []):


In [2]:
# get the environment
env = gym.make('CartPole-v0')

In [3]:
# put yourself in the start state
# it also returns the state
env.reset()
# Out[50]: array([-0.04533731, -0.03231478, -0.01469216,  0.04151   ])

# what do the state variables mean?
# Num Observation Min Max
# 0 Cart Position -2.4  2.4
# 1 Cart Velocity -Inf  Inf
# 2 Pole Angle  ~ -41.8°  ~ 41.8°
# 3 Pole Velocity At Tip  -Inf  Inf

array([-0.04140599,  0.04666093,  0.02398624, -0.02121128], dtype=float32)

In [4]:
box = env.observation_space

# In [53]: box
# Out[53]: Box(4,)

# In [54]: box.
# box.contains       box.high           box.sample         box.to_jsonable
# box.from_jsonable  box.low            box.shape

In [7]:
env.action_space

# In [71]: env.action_space
# Out[71]: Discrete(2)

# In [72]: env.action_space.
# env.action_space.contains       env.action_space.n              env.action_space.to_jsonable
# env.action_space.from_jsonable  env.action_space.sample

Discrete(2)

In [72]:
num_episodes = 500
steps_taken = []
for i in range(num_episodes):
    # reset the environment
    env.reset()
    # run through an episode
    done = False
    num_steps = 0
    while not done:
        observation, reward, done, _ = env.step(env.action_space.sample())
        num_steps +=1
    steps_taken.append(num_steps)

In [73]:
sum(steps_taken)/len(steps_taken)

21.97

In [47]:
steps_taken

[19,
 16,
 21,
 10,
 26,
 12,
 22,
 26,
 13,
 14,
 33,
 26,
 26,
 19,
 16,
 26,
 22,
 17,
 16,
 19,
 17,
 58,
 29,
 27,
 13,
 27,
 16,
 15,
 13,
 17,
 12,
 31,
 19,
 32,
 18,
 22,
 21,
 20,
 25,
 21,
 11,
 16,
 14,
 17,
 13,
 20,
 25,
 93,
 33,
 26]

In [36]:
import numpy as np

In [42]:
a = np.random.random()
b = np.random.random(4)
c = b*2
d = c - 1

In [44]:
print(b)
print(c)
print(d)

[0.53141064 0.65270693 0.3507735  0.80273248]
[1.06282127 1.30541385 0.70154699 1.60546496]
[ 0.06282127  0.30541385 -0.29845301  0.60546496]


In [74]:
env.action_space.contains(1)

True

In [77]:
env.observation_space.contains([0.7,  3,  0.02398624, -0.02121128])

True

In [67]:
env.observation_space.sample()

array([-3.9756763e+00, -1.6804278e+38, -1.6399813e-01, -2.8834977e+37],
      dtype=float32)

In [78]:
env.reset()

array([ 0.0473399 ,  0.00018199, -0.03522669, -0.02411438], dtype=float32)

In [79]:
env.reset()

array([-0.03188613, -0.0453225 , -0.02424021,  0.02232612], dtype=float32)

In [80]:
env.reset()

array([ 0.02147732,  0.0333949 , -0.0137676 ,  0.00102687], dtype=float32)

In [84]:
np.empty(4)

array([-0.03188613, -0.0453225 , -0.02424021,  0.02232612])