In [1]:
from sklearn.linear_model import SGDRegressor

In [2]:
model = SGDRegressor()

In [3]:
model.partial_fit([[0,0]],[0])

SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=1000,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [5]:
model.predict([[0,0]])

array([0.])

In [6]:
model.predict([[99,99]])

array([0.])

In [7]:
model.predict([[-0.567,-0.890]])

array([0.])

In [38]:
import numpy as np
import pandas as pd

In [24]:
for i in range(5):
    print(np.random.randint(1, 2))

1
1
1
1
1


In [17]:
np.random.randint(3, size=4)

array([0, 0, 1, 0])

In [19]:
np.random.randint([1, 5, 7], 10)

array([3, 8, 7])

In [25]:
[t for t in range(1, 8)]

[1, 2, 3, 4, 5, 6, 7]

In [27]:
[0 for t in range(1,8)]

[0, 0, 0, 0, 0, 0, 0]

In [28]:
backlog = dict(zip([t for t in range(1, 8)],
                            [0 for t in range(1,8)]))

In [29]:
backlog

{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}

In [34]:
np.random.randint(1, 6, 3)

array([3, 1, 2])

In [42]:
jtime = np.random.randint(1, 7, 8)
jtime

array([2, 3, 3, 4, 6, 3, 1, 5])

In [43]:
uniques = pd.DataFrame(jtime)[0].value_counts()
uniques

3    3
6    1
5    1
4    1
2    1
1    1
Name: 0, dtype: int64