In [1]:
from sklearn.linear_model import SGDRegressor

In [2]:
model = SGDRegressor()

In [3]:
model.partial_fit([[0,0]],[0])

SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=1000,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [5]:
model.predict([[0,0]])

array([0.])

In [6]:
model.predict([[99,99]])

array([0.])

In [7]:
model.predict([[-0.567,-0.890]])

array([0.])

In [2]:
import numpy as np
import pandas as pd

In [24]:
for i in range(5):
    print(np.random.randint(1, 2))

1
1
1
1
1


In [17]:
np.random.randint(3, size=4)

array([0, 0, 1, 0])

In [19]:
np.random.randint([1, 5, 7], 10)

array([3, 8, 7])

In [25]:
[t for t in range(1, 8)]

[1, 2, 3, 4, 5, 6, 7]

In [27]:
[0 for t in range(1,8)]

[0, 0, 0, 0, 0, 0, 0]

In [28]:
backlog = dict(zip([t for t in range(1, 8)],
                            [0 for t in range(1,8)]))

In [29]:
backlog

{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}

In [34]:
np.random.randint(1, 6, 3)

array([3, 1, 2])

In [42]:
jtime = np.random.randint(1, 7, 8)
jtime

array([2, 3, 3, 4, 6, 3, 1, 5])

In [43]:
uniques = pd.DataFrame(jtime)[0].value_counts()
uniques

3    3
6    1
5    1
4    1
2    1
1    1
Name: 0, dtype: int64

In [4]:
for i in range(100):
    if np.random.randint(1, 2):
        a = np.random.randint(1, 7)
        print('hey')
    else:
        b = np.random.randint(1, 8)
        print('ho')

hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey
hey


In [9]:
jtime = np.random.randint(1, 15, 30)
jtime

array([ 5,  3, 11,  3,  3,  5,  7, 14, 14, 13,  1,  9,  2,  6,  3,  6,  2,
       10,  8,  1,  9, 12, 13,  7,  5, 10,  8, 13,  9,  1])

In [10]:
pd.DataFrame(jtime)[0].value_counts()

3     4
13    3
9     3
5     3
1     3
14    2
10    2
8     2
7     2
6     2
2     2
12    1
11    1
Name: 0, dtype: int64

In [39]:
n = 5
mr = 3
mt = 7

In [40]:
matrix1 = pd.DataFrame(np.zeros((n*mt, mr)))

In [41]:
req = np.random.randint(0, mr+1, n)
r1 = 1
r1

1

In [42]:
matrix1.iloc[0:7, 0:r1] = 2

In [43]:
matrix1

0    1    2
0   2.0  0.0  0.0
1   2.0  0.0  0.0
2   2.0  0.0  0.0
3   2.0  0.0  0.0
4   2.0  0.0  0.0
5   2.0  0.0  0.0
6   2.0  0.0  0.0
7   0.0  0.0  0.0
8   0.0  0.0  0.0
9   0.0  0.0  0.0
10  0.0  0.0  0.0
11  0.0  0.0  0.0
12  0.0  0.0  0.0
13  0.0  0.0  0.0
14  0.0  0.0  0.0
15  0.0  0.0  0.0
16  0.0  0.0  0.0
17  0.0  0.0  0.0
18  0.0  0.0  0.0
19  0.0  0.0  0.0
20  0.0  0.0  0.0
21  0.0  0.0  0.0
22  0.0  0.0  0.0
23  0.0  0.0  0.0
24  0.0  0.0  0.0
25  0.0  0.0  0.0
26  0.0  0.0  0.0
27  0.0  0.0  0.0
28  0.0  0.0  0.0
29  0.0  0.0  0.0
30  0.0  0.0  0.0
31  0.0  0.0  0.0
32  0.0  0.0  0.0
33  0.0  0.0  0.0
34  0.0  0.0  0.0

In [107]:
n = 8
mr = 12
mt = 7
time = 6
req1 = np.random.randint(0, mr+1, n)
r1 = req1[3]
req2 = np.random.randint(0, mr+1, n)
r2 = req2[3]

In [108]:
print("n:",n," mr:",mr," mt:",mt," time:",time," r1:",r1," r2:",r2)

n: 8  mr: 12  mt: 7  time: 6  r1: 10  r2: 8


In [109]:
def generate_job_matrix(n, mr, mt, time, r1, r2):
    rows = n * mt
    columns = mr
    matrix1 = pd.DataFrame(np.zeros((n*mt, mr)))
    matrix1.iloc[0:time, 0:r1] = time
    matrix2 = pd.DataFrame(np.zeros((n*mt, mr)))
    matrix2.iloc[0:time, 0:r2] = time
    return matrix1, matrix2

In [110]:
matrix1, matrix2 = generate_job_matrix(n, mr, mt, time, r1, r2)

In [111]:
#matrix1

In [112]:
#matrix2

In [113]:
(not matrix1.any().any()) and (not matrix2.any().any())

False

In [114]:
#matrix1.any()

In [115]:
keys = ['resource1', 'resource2']
for i in range(1, 4):
    keys.append(f'job{i}')
keys.append('backlog')
keys

['resource1', 'resource2', 'job1', 'job2', 'job3', 'backlog']

In [116]:
jlist1 = []
jlist2 = []

In [117]:
def generate_job_matrix(time, r1, r2):
    rows = n * mt
    columns = mr
    matrix1 = pd.DataFrame(np.zeros((n*mt, mr)))
    matrix1.iloc[0:time, 0:r1] = time
    matrix2 = pd.DataFrame(np.zeros((n*mt, mr)))
    matrix2.iloc[0:time, 0:r2] = time
    return matrix1, matrix2

In [118]:
backlog = dict(zip([t for t in range(1, mt+1)],[0 for t in range(1,mt+1)]))

In [119]:
jtime = np.random.randint(1, mt+1, n)
uniques = pd.DataFrame(jtime)[0].value_counts()
resource1_req = np.random.randint(0, mr+1, n)
resource2_req = np.random.randint(0, mr+1, n)
index = 0
for time in range(1, mt+1):
    if time in uniques.index:
        backlog[time] += uniques[time] - 1
        uniques[time] = 0
        r1, r2 = resource1_req[index], resource2_req[index]
        m1, m2 = generate_job_matrix(time, r1, r2)
        jlist1.append(m1)
        jlist2.append(m2)
        index += 1

In [120]:
def generate_resource_matrix():
    rMatrix1 = pd.DataFrame(np.zeros((n*mt, mr)))
    rMatrix2 = pd.DataFrame(np.zeros((n*mt, mr)))
    return rMatrix1, rMatrix2

In [121]:
rMatrix1, rMatrix2 = generate_resource_matrix()

In [123]:
keys = ['resource1', 'resource2']
for i in range(1, mt+1):
    keys.append(f'job{i}')
keys.append('backlog')
values = [rMatrix1, rMatrix2]
for m1, m2 in zip(jlist1, jlist2):
    subKeys = ['r1', 'r2']
    subValues = [m1, m2]
    values.append(dict(zip(subKeys, subValues)))
values.append(backlog)
answer = dict(zip(keys, values)) 

In [124]:
answer

{'resource1':       0    1    2    3    4    5    6    7    8    9   10   11
 0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 14  0.0  0.0  0.0  0.0  0.

In [125]:
answer.keys()

dict_keys(['resource1', 'resource2', 'job1', 'job2', 'job3', 'job4', 'job5', 'job6'])

In [127]:
answer['job5']

{'r1':       0    1    2    3    4    5    6    7    8    9   10   11
 0   7.0  7.0  7.0  7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1   7.0  7.0  7.0  7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 2   7.0  7.0  7.0  7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 3   7.0  7.0  7.0  7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 4   7.0  7.0  7.0  7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 5   7.0  7.0  7.0  7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 6   7.0  7.0  7.0  7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 14  0.0  0.0  0.0  0.0  0.0  0.0 

In [138]:
values[7]

{1: 0, 2: 1, 3: 0, 4: 1, 5: 0, 6: 0, 7: 1}

In [139]:
len(values)

8